name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v7
      - run: uvx --from build pyproject-build --sdist --wheel
      - run: uvx twine check dist/*
      - uses: actions/upload-artifact@v7
        with:
          path: dist/*
  pytest:
    name: PyTest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
        django-version:
          - "5.2" # LTS
          - "6.0"
        exclude:
          - python-version: "3.10"
            django-version: "6.0"
          - python-version: "3.11"
            django-version: "6.0"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v7
        with:
          node-version: "lts/*"
      - run: |
          cd tests
          npm install
      - run: uv run --no-dev --group=test tests/manage.py collectstatic --noinput
      - run: uv run --no-dev --group=test --with Django~=${{ matrix.django-version }}.0 pytest
      - uses: codecov/codecov-action@v7
        with:
          use_oidc: true
          flags: python-${{ matrix.python-version }}-django-${{ matrix.django-version }}
  pytest-extras:
    name: PyTest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        python-version:
          - "3.12"
        extra:
          - "whitenoise"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v7
        with:
          node-version: "lts/*"
      - run: |
          cd tests
          npm install
      - run: uv run --no-dev --group=test tests/manage.py collectstatic --noinput
      - run: uv run --no-dev --group=test --extra=${{ matrix.extra }} pytest
      - uses: codecov/codecov-action@v7
        with:
          use_oidc: true
          flags: python-${{ matrix.python-version }}-${{ matrix.extra }}
